---
# handlers file for bootstrap
- name: restart sshd
  service: name=ssh state=restarted

- name: reload ufw
  ufw: state=reloaded
  ignore_errors: yes

- name: restart postgres
  service: name=postgres state=restart
