#  - repo: https://github.com/drwetter/testssl.sh
#    dest: testssl.sh
#    tags: ssl, tls, ciphers

tools_dir: /tools

kali_templates:
  - src: tools.txt.j2
    dest: /tools/tools.txt
    mode: "0644"

kali_git_repositories:
  - repo: https://github.com/bugcrowd/HUNT.git
    dest: hunt
    tags: web, webapps, burp
  - repo: https://github.com/PowerShellMafia/PowerSploit.git
    dest: powersploit
    tags: powershell, post exploitation, windows, active directory, ad, priv esc
  - repo: https://github.com/SpiderLabs/Responder.git
    dest: responder
    tags: responder, LLMNR, NBT-NS, mDNS, poisoner, hashes, gather
  - repo: https://github.com/trustedsec/unicorn.git
    dest: unicorn
    tags: powershell, shell, msf, metasploit

kali_binary_downloads:
  - url: https://github.com/gentilkiwi/mimikatz/releases/download/2.1.1-20171220/mimikatz_trunk.zip
    dest: binaries/mimikatz_trunk.zip
  - url: https://download.sysinternals.com/files/SysinternalsSuite.zip
    dest: binaries/sysinternals-suite.zip
  - url: https://jitpack.io/com/github/frohoff/ysoserial/master-SNAPSHOT/ysoserial-master-SNAPSHOT.jar
    dest: binaries/ysoserial-master.jar
  
kali_burpapp_downloads:
  - url: https://portswigger.net/bappstore/bapps/download/67f5c31f93d04ad3a3b0a1808b3648fa
    dest: elasticburp
  - url: https://portswigger.net/bappstore/bapps/download/f9bbac8c4acf4aefa4d7dc92a991af2f
    dest: autorize
