---
- name: Install mkdocs
  pip:
    name={{ item }}
    state=present
  with_items:
    - mkdocs
    - mkdocs-material

- name: Create directory
  file:
    path: '{{ docs_dir }}'
    state: directory
    mode: 0755
    owner: "{{ docs_user }}"
    group: "{{ docs_user }}"

- name: Copy all markdown files
  #shell: find {{ tools_dir|quote }}/ -name '*.csv' | cpio -pdm  {{ docs_dir|quote }}
  shell: find {{ tools_dir|quote }}/ -name '*.md' -exec cp --parents \{\} {{ docs_dir|quote }} \;

- name: upload mkdocs template
  template:
    src=mkdocs.yml.j2
    dest={{ docs_dir }}/mkdocs.yml
    mode=0755
    owner={{ docs_user }}
    group={{ docs_user }}

